package com.parking.app.ui.screens.registration

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.CalendarToday
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.CreditCard
import androidx.compose.material.icons.filled.PersonAdd
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.parking.app.ui.components.AlertBox
import com.parking.app.ui.components.AlertTone
import com.parking.app.ui.components.BackToMenuButton
import com.parking.app.ui.components.CardSectionTitle
import com.parking.app.ui.components.LabelValueRow
import com.parking.app.ui.components.SectionHeader
import com.parking.app.ui.components.ShadcnCard
import com.parking.app.ui.components.StatusPill
import com.parking.app.ui.components.StatusTone
import com.parking.app.ui.theme.AccentPalette
import com.parking.app.ui.theme.LocalSemanticColors
import com.parking.app.ui.theme.LocalSpacing

/**
 * Registro de Nuevo Cliente — Port de `ClientRegistration.tsx`.
 * Form en 3 cards: Info Personal · Plan & Vehículo · Pago.
 * Al completar muestra una "tarjeta de cliente" generada con gradient azul.
 */
@Composable
fun ClientRegistrationScreen(onBack: () -> Unit) {
    val spacing = LocalSpacing.current
    var form by remember { mutableStateOf(ClientForm()) }
    var generated by remember { mutableStateOf<GeneratedCard?>(null) }
    Column(verticalArrangement = Arrangement.spacedBy(spacing.l)) {
        Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(spacing.m)) {
            BackToMenuButton(onClick = onBack)
            SectionHeader(
                title = "Registro de Nuevo Cliente",
                description = "Complete la información para crear un nuevo cliente alquilado.",
            )
        }
        val card = generated
        if (card == null) {
            Row(horizontalArrangement = Arrangement.spacedBy(spacing.l), modifier = Modifier.fillMaxWidth()) {
                PersonalCard(form = form, onChange = { form = it }, modifier = Modifier.weight(1f))
                PlanAndVehicleCard(form = form, onChange = { form = it }, modifier = Modifier.weight(1f))
            }
            PaymentNotesCard(
                form = form,
                onChange = { form = it },
                onSubmit = {
                    generated = GeneratedCard(
                        cardNumber = "PKS${kotlinx.datetime.Clock.System.now().toEpochMilliseconds().toString().takeLast(6)}",
                        clientId = "CLI${kotlinx.datetime.Clock.System.now().toEpochMilliseconds().toString().takeLast(5)}",
                    )
                },
            )
        } else {
            AlertBox(
                title = "¡Registro completado exitosamente!",
                text = "El cliente ha sido registrado en el sistema y su tarjeta ha sido generada.",
                icon = Icons.Filled.CheckCircle,
                tone = AlertTone.Success,
            )
            GeneratedCardView(card = card, form = form, onMore = { generated = null; form = ClientForm() })
            ClientSummaryCard(form = form, plan = planFor(form.planType))
        }
    }
}

private data class ClientForm(
    val firstName: String = "",
    val lastName: String = "",
    val documentType: String = "Cédula de Ciudadanía",
    val documentNumber: String = "",
    val email: String = "",
    val phone: String = "",
    val address: String = "",
    val planType: String = "",
    val startDate: String = "",
    val assignedSpace: String = "",
    val vehiclePlate: String = "",
    val vehicleType: String = "",
    val vehicleBrand: String = "",
    val vehicleModel: String = "",
    val vehicleColor: String = "",
    val paymentMethod: String = "",
    val notes: String = "",
) {
    val isValid: Boolean
        get() = firstName.isNotBlank() && lastName.isNotBlank() && documentNumber.isNotBlank() &&
            email.isNotBlank() && phone.isNotBlank() && planType.isNotBlank() && startDate.isNotBlank() &&
            assignedSpace.isNotBlank() && vehiclePlate.isNotBlank() && vehicleType.isNotBlank() && paymentMethod.isNotBlank()
}

private data class GeneratedCard(val cardNumber: String, val clientId: String)

private data class PlanInfo(val label: String, val priceCents: Long, val days: Int, val discountPct: Int)

private val planOptions = listOf(
    PlanInfo("Mensual", 45_000_00L, 30, 0),
    PlanInfo("Trimestral", 120_000_00L, 90, 7),
    PlanInfo("Semestral", 230_000_00L, 180, 10),
    PlanInfo("Anual", 420_000_00L, 365, 17),
)

private fun planFor(key: String): PlanInfo? = planOptions.firstOrNull { it.label == key }

@Composable
private fun PersonalCard(form: ClientForm, onChange: (ClientForm) -> Unit, modifier: Modifier = Modifier) {
    val spacing = LocalSpacing.current
    ShadcnCard(modifier = modifier) {
        Column(modifier = Modifier.padding(spacing.l), verticalArrangement = Arrangement.spacedBy(spacing.m)) {
            CardSectionTitle(
                title = "Información Personal",
                description = "Datos básicos del cliente.",
                icon = Icons.Filled.PersonAdd,
                palette = AccentPalette.Blue,
            )
            Row(horizontalArrangement = Arrangement.spacedBy(spacing.s)) {
                OutlinedTextField(value = form.firstName, onValueChange = { onChange(form.copy(firstName = it)) }, label = { Text("Nombres *") }, singleLine = true, modifier = Modifier.weight(1f))
                OutlinedTextField(value = form.lastName, onValueChange = { onChange(form.copy(lastName = it)) }, label = { Text("Apellidos *") }, singleLine = true, modifier = Modifier.weight(1f))
            }
            Row(horizontalArrangement = Arrangement.spacedBy(spacing.s)) {
                OutlinedTextField(value = form.documentType, onValueChange = { onChange(form.copy(documentType = it)) }, label = { Text("Tipo Doc.") }, singleLine = true, modifier = Modifier.weight(1f))
                OutlinedTextField(value = form.documentNumber, onValueChange = { onChange(form.copy(documentNumber = it.filter(Char::isLetterOrDigit))) }, label = { Text("Número *") }, singleLine = true, modifier = Modifier.weight(1f))
            }
            OutlinedTextField(value = form.email, onValueChange = { onChange(form.copy(email = it)) }, label = { Text("Correo Electrónico *") }, singleLine = true, modifier = Modifier.fillMaxWidth())
            OutlinedTextField(value = form.phone, onValueChange = { onChange(form.copy(phone = it.filter { c -> c.isDigit() || c == '-' || c == ' ' })) }, label = { Text("Teléfono *") }, singleLine = true, modifier = Modifier.fillMaxWidth())
            OutlinedTextField(value = form.address, onValueChange = { onChange(form.copy(address = it)) }, label = { Text("Dirección") }, minLines = 2, modifier = Modifier.fillMaxWidth())
        }
    }
}

@Composable
private fun PlanAndVehicleCard(form: ClientForm, onChange: (ClientForm) -> Unit, modifier: Modifier = Modifier) {
    val spacing = LocalSpacing.current
    val semantic = LocalSemanticColors.current
    ShadcnCard(modifier = modifier) {
        Column(modifier = Modifier.padding(spacing.l), verticalArrangement = Arrangement.spacedBy(spacing.m)) {
            CardSectionTitle(
                title = "Plan y Vehículo",
                description = "Configuración del plan y datos del vehículo.",
                icon = Icons.Filled.CalendarToday,
                palette = AccentPalette.Green,
            )
            // Picker simple de planes (no usamos M3 ExposedDropdown para minimizar superficie).
            Column(verticalArrangement = Arrangement.spacedBy(spacing.xs)) {
                Text("Tipo de Plan *", style = MaterialTheme.typography.labelMedium, color = MaterialTheme.colorScheme.onSurfaceVariant)
                Row(horizontalArrangement = Arrangement.spacedBy(spacing.xs)) {
                    planOptions.forEach { plan ->
                        val selected = form.planType == plan.label
                        Box(
                            modifier = Modifier
                                .weight(1f)
                                .clip(RoundedCornerShape(8.dp))
                                .background(if (selected) semantic.greenContainer else MaterialTheme.colorScheme.surface)
                                .border(1.dp, if (selected) semantic.greenAccent else MaterialTheme.colorScheme.outlineVariant, RoundedCornerShape(8.dp))
                                .clickable { onChange(form.copy(planType = plan.label)) }
                                .padding(spacing.s),
                        ) {
                            Column {
                                Text(plan.label, style = MaterialTheme.typography.bodyMedium.copy(fontWeight = FontWeight.SemiBold))
                                Text(com.parking.shared.domain.model.Money(plan.priceCents).formatCop(), style = MaterialTheme.typography.bodySmall, color = semantic.greenAccent)
                                if (plan.discountPct > 0) Text("${plan.discountPct}% OFF", style = MaterialTheme.typography.labelSmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                            }
                        }
                    }
                }
            }
            Row(horizontalArrangement = Arrangement.spacedBy(spacing.s)) {
                OutlinedTextField(value = form.startDate, onValueChange = { onChange(form.copy(startDate = it)) }, label = { Text("Fecha Inicio *") }, placeholder = { Text("YYYY-MM-DD") }, singleLine = true, modifier = Modifier.weight(1f))
                OutlinedTextField(value = form.assignedSpace, onValueChange = { onChange(form.copy(assignedSpace = it.uppercase())) }, label = { Text("Plaza Asignada *") }, placeholder = { Text("A-15") }, singleLine = true, modifier = Modifier.weight(1f))
            }
            Text("Información del Vehículo", style = MaterialTheme.typography.titleSmall.copy(fontWeight = FontWeight.SemiBold))
            Row(horizontalArrangement = Arrangement.spacedBy(spacing.s)) {
                OutlinedTextField(value = form.vehiclePlate, onValueChange = { onChange(form.copy(vehiclePlate = it.uppercase().filter(Char::isLetterOrDigit).take(10))) }, label = { Text("Placa *") }, singleLine = true, modifier = Modifier.weight(1f))
                OutlinedTextField(value = form.vehicleType, onValueChange = { onChange(form.copy(vehicleType = it)) }, label = { Text("Tipo *") }, placeholder = { Text("Automóvil / Moto") }, singleLine = true, modifier = Modifier.weight(1f))
            }
            Row(horizontalArrangement = Arrangement.spacedBy(spacing.s)) {
                OutlinedTextField(value = form.vehicleBrand, onValueChange = { onChange(form.copy(vehicleBrand = it)) }, label = { Text("Marca") }, singleLine = true, modifier = Modifier.weight(1f))
                OutlinedTextField(value = form.vehicleModel, onValueChange = { onChange(form.copy(vehicleModel = it)) }, label = { Text("Modelo") }, singleLine = true, modifier = Modifier.weight(1f))
                OutlinedTextField(value = form.vehicleColor, onValueChange = { onChange(form.copy(vehicleColor = it)) }, label = { Text("Color") }, singleLine = true, modifier = Modifier.weight(1f))
            }
        }
    }
}

@Composable
private fun PaymentNotesCard(form: ClientForm, onChange: (ClientForm) -> Unit, onSubmit: () -> Unit) {
    val spacing = LocalSpacing.current
    ShadcnCard {
        Column(modifier = Modifier.padding(spacing.l), verticalArrangement = Arrangement.spacedBy(spacing.m)) {
            CardSectionTitle(
                title = "Información de Pago y Notas",
                description = null,
                icon = Icons.Filled.CreditCard,
                palette = AccentPalette.Purple,
            )
            Row(horizontalArrangement = Arrangement.spacedBy(spacing.s), modifier = Modifier.fillMaxWidth()) {
                OutlinedTextField(
                    value = form.paymentMethod,
                    onValueChange = { onChange(form.copy(paymentMethod = it)) },
                    label = { Text("Método de Pago *") },
                    placeholder = { Text("Efectivo / Tarjeta / Transferencia") },
                    singleLine = true,
                    modifier = Modifier.weight(1f),
                )
                Button(
                    onClick = onSubmit,
                    enabled = form.isValid,
                    modifier = Modifier.weight(1f).height(56.dp),
                ) { Text("Registrar Cliente", fontWeight = FontWeight.SemiBold) }
            }
            OutlinedTextField(
                value = form.notes,
                onValueChange = { onChange(form.copy(notes = it)) },
                label = { Text("Notas Adicionales") },
                minLines = 3,
                modifier = Modifier.fillMaxWidth(),
            )
        }
    }
}

@Composable
private fun GeneratedCardView(card: GeneratedCard, form: ClientForm, onMore: () -> Unit) {
    val spacing = LocalSpacing.current
    val semantic = LocalSemanticColors.current
    ShadcnCard {
        Column(modifier = Modifier.padding(spacing.l), verticalArrangement = Arrangement.spacedBy(spacing.m)) {
            Text("Tarjeta de Cliente Generada", style = MaterialTheme.typography.titleLarge.copy(fontWeight = FontWeight.SemiBold))
            // "Tarjeta" estilo gradient
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .clip(RoundedCornerShape(14.dp))
                    .background(semantic.blueAccent)
                    .padding(spacing.l),
            ) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Column(modifier = Modifier.weight(1f)) {
                        Text("ParkSmart", style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.Bold), color = Color.White)
                        Text("Cliente Alquilado", style = MaterialTheme.typography.bodySmall, color = Color.White.copy(alpha = 0.85f))
                    }
                    StatusPill(label = form.planType.ifBlank { "Mensual" }, tone = StatusTone.Neutral, showDot = false)
                }
                Spacer(Modifier.height(spacing.m))
                Text(
                    card.cardNumber,
                    style = MaterialTheme.typography.headlineSmall.copy(fontWeight = FontWeight.Bold),
                    color = Color.White,
                )
                Spacer(Modifier.height(spacing.xs))
                Text("${form.firstName} ${form.lastName}".uppercase(), style = MaterialTheme.typography.titleMedium, color = Color.White)
                Spacer(Modifier.height(spacing.m))
                Row(horizontalArrangement = Arrangement.spacedBy(spacing.l), modifier = Modifier.fillMaxWidth()) {
                    Column(modifier = Modifier.weight(1f)) {
                        Text("Plaza Asignada", style = MaterialTheme.typography.labelSmall, color = Color.White.copy(alpha = 0.7f))
                        Text(form.assignedSpace, style = MaterialTheme.typography.titleLarge.copy(fontWeight = FontWeight.Bold), color = Color.White)
                    }
                    Column(modifier = Modifier.weight(1f)) {
                        Text("Cliente ID", style = MaterialTheme.typography.labelSmall, color = Color.White.copy(alpha = 0.7f))
                        Text(card.clientId, style = MaterialTheme.typography.bodyMedium, color = Color.White)
                    }
                }
            }
            Row(horizontalArrangement = Arrangement.spacedBy(spacing.s)) {
                androidx.compose.material3.OutlinedButton(onClick = { }, modifier = Modifier.weight(1f)) { Text("Imprimir Tarjeta") }
                Button(onClick = onMore, modifier = Modifier.weight(1f)) { Text("Registrar Otro Cliente") }
            }
        }
    }
}

@Composable
private fun ClientSummaryCard(form: ClientForm, plan: PlanInfo?) {
    val spacing = LocalSpacing.current
    ShadcnCard {
        Column(modifier = Modifier.padding(spacing.l), verticalArrangement = Arrangement.spacedBy(spacing.s)) {
            Text("Resumen del Cliente", style = MaterialTheme.typography.titleMedium.copy(fontWeight = FontWeight.SemiBold))
            LabelValueRow("Nombre Completo:", "${form.firstName} ${form.lastName}")
            LabelValueRow("Documento:", "${form.documentType}: ${form.documentNumber}")
            LabelValueRow("Email:", form.email)
            LabelValueRow("Teléfono:", form.phone)
            LabelValueRow("Vehículo:", "${form.vehiclePlate} — ${form.vehicleBrand} ${form.vehicleModel}".trim())
            LabelValueRow("Plan:", "${form.planType}${plan?.let { " — ${com.parking.shared.domain.model.Money(it.priceCents).formatCop()}" } ?: ""}", accent = true)
        }
    }
}

/** Versión sin handlers — usada cuando se renderiza dentro del shell. */
@Composable
fun ClientRegistrationScreen() {
    ClientRegistrationScreen(onBack = { })
}
